# Properties to be used on the UAT environment


sfdc:
  password: "![]"
  securityToken: "![]"
  consumerKey: "![]"
  consumerSecret: "![]"
  
# SAP S/4HANA Cloud Connector
sap:
  s4hana.password: "![]"