#%RAML 1.0 DataType
type: object
properties:
  Owner: !include extendedAttributes.raml
  PDLM__Item_Revision__r: !include extendedAttributes.raml
  PDLM__Last_Modified_Date__c: string
  LastModifiedDate: string
  PDLM__File_Extension__c: string
  PDLM__Content_Id__c: string
  PDLM__Document_Title__c: string
  PDLM__Version_Number__c: string
  CreatedDate: string
  OwnerId: string 
  PDLM__Document_Size__c: number
  PDLM__Document_Version__c: string
  PDLM__Item_Revision__c: string
  Id: string