#%RAML 1.0 DataType
type: object
properties:
  PDLM__Item_Revision__r: !include extendedAttributes.raml
  PDLM__Item__r: !include pdlmItem.raml
  PDLM__Item_Revision__c: string
  PDLM__Find_Number__c: number
  PDLM__Quantity__c: number
  PDLM__Item__c: string
  Parent_Item_Number__c: string
  Id: string