#%RAML 1.0 DataType
type: object
properties:
  attributes?: !include attributes.raml
  LastModifiedDate?: nil | string
  PDLM__Rebate__c?: nil | string | number
  Opportunity__c?: nil | string | number
  PDLM__Current_Quarter_Spend__c?: number | integer
  PDLM__Revision_Count__c?: number | integer
  Related_Request__c?: nil | string | number
  PDLM__Latest_Released_Revision__c?: nil | string
  Name?: nil | string
  PDLM__Markup_Percentage__c?: nil | string | number
  PDLM__Latest_Revision__c?: nil | string
  PDLM_Inventory_c__c?: nil | string | number
  PDLM__Category_Name__c?: nil | string
  CreatedById?: nil | string
  PDLM__Has_Bom__c?: boolean
  PDLM__Image__c?: nil | string
  PDLM__Standard_Cost__c?: number | integer
  PDLM__Product__c?: nil | string | number
  PDLM__Item_Revisions__r?: !include itemRevisions.raml
  IsDeleted?: boolean
  PDLM__Price_Book__c?: nil | string | number
  PDLM__External_Image__c?: nil | string | number
  PDLM__Has_Attachments__c?: boolean
  LastViewedDate?: nil | string | number
  PDLM__Pending_Revisions__c?: number | integer
  PDLM__Primary_Key__c?: nil | string
  PDLM__Has_Aml__c?: boolean
  PDLM__Revision__c?: nil | string
  PDLM__Sharing_Rules__c?: nil | string | number
  PDLM__Category__r?: !include extendedAttributes.raml
  Standard_Cost_for_History__c?: number | integer
  CreatedDate?: nil | string
  PDLM__Thumbnail__c?: nil | string
  PDLM__Category__c?: nil | string
  Id: string
  Lifecycle__c?: nil | string
  Quality_Issues__c?: nil | string | number
  PDLM__Description__c?: nil | string
  PDLM__Has_Quality__c?: boolean
  PDLM__Thumbnail_img__c?: nil | string
  LastReferencedDate?: nil | string | number
  PDLM__External_Link__c?: nil | string | number
  PDLM__Name_Unique__c?: nil | string
  OwnerId?: nil | string
  PDLM__Revisions_Draft__c?: number | integer
  PDLM__Has_Pending_Revision__c?: boolean
  PDLM__BOM_Cost__c?: number | integer
  PDLM__Current_Quarter_Demand__c?: nil | string | number
  SystemModstamp?: nil | string
  PDLM__Has_Open_Quality__c?: boolean
  LastActivityDate?: nil | string | number
  PDLM__Latest_Lifecycle_Phase__c?: nil | string
  PDLM__Has_Parent__c?: boolean
  PDLM__Manufacturer_Key__c?: nil | string | number
  PDLM__Autonumber__c?: nil | string | number
  PDLM__On_Change_cb__c?: boolean
  PDLM__Owner_Name__c?: nil | string
  LastModifiedById?: nil | string
  PDLM__On_Change__c?: boolean
  