#%RAML 1.0 DataType
type: object
properties:
  attributes?: !include attributes.raml
  LastModifiedDate?: nil | string
  Bottom_Bracket_Height2__c?: nil | string | number
  Seat_Tube_Length__c?: nil | string
  PDLM__Phase_Unique__c?: nil | string
  Seat_Tube_Length2__c?: nil | string
  PDLM__Detailed_Description__c?: nil | string
  Opportunity__c?: nil | string
  Package__c?: nil | string
  Length_Std__c?: nil | string | number
  PDLM__Has_Bom__c?: boolean
  Stack2__c?: nil | string
  Wheelbase__c?: nil | string
  IsDeleted?: boolean
  Reach2__c?: nil | string
  PDLM__Has_Attachments__c?: boolean
  Height_Metric__c?: nil | string
  Change_Type__c?: nil | string
  Model__c?: nil | string
  Chain_Stay_Length__c?: nil | string
  PDLM__Training_Required__c?: boolean
  PDLM__Has_Aml__c?: boolean
  PDLM__Revision__c?: nil | string
  PDLM__Expired__c?: boolean
  PDLM__Is_Latest__c?: boolean
  PCB_Footprint__c?: nil | string
  PDLM__Training_Quiz__c?: nil | string
  PDLM__Category__c?: nil | string
  Id: string
  Serial_Number__c?: nil | string
  PDLM__Completeness__c?: nil | string
  Department__c?: nil | string
  Lifecycle__c?: nil | string
  Tolerance__c?: nil | string
  Price_Adjustment__c?: nil | string | number
  Head_Tube_Angle__c?: nil | string
  Total_Cost__c?: nil | string | number
  PDLM__Has_Quality__c?: boolean
  Seat_Tube_Angle2__c?: nil | string
  PDLM__End_Date_Time__c?: nil | string
  PDLM__Related_Change__c?: nil | string
  Reach__c?: nil | string
  Require_Additional_Signer_to_Sign_off__c?: boolean
  Supporting_Documentation_Required__c?: boolean
  PDLM__Is_Latest_Released__c?: boolean
  Custom_Field2__c?: nil | string
  Weight_Std__c?: nil | string
  PDLM__Revision_Status__c?: nil | string
  Height_Std__c?: nil | string
  PDLM__Cancelled__c?: boolean
  Value__c?: nil | string
  Indirect_Cost__c?: nil | string | number
  put_a_number_here_for_fun__c?: nil | string | number
  Stack__c?: nil | string
  Direct_Cost__c?: nil | string | number
  Stand_Over_Height__c?: nil | string
  SystemModstamp?: nil | string
  Item_Number__c?: nil | string
  PDLM__Training_Due_Date__c?: nil | string
  Length_Metric__c?: nil | string
  PDLM__Has_Open_Quality__c?: boolean
  Target_Margin__c?: nil | string
  LastActivityDate?: nil | string
  Update_Prices__c?: boolean
  Size__c?: nil | string | number
  Change_Percentage__c?: nil | string
  Top_Tube_Length__c?: nil | string
  PDLM__On_Change__c?: boolean
  Top_Tube_Length2__c?: nil | string
  Wheelbase2__c?: nil | string
  PDLM__Cost__c?: nil | string | number
  Tech_Specs__c?: nil | string
  Project__c?: nil | string
  Additional_Signer__c?: nil | string
  Serialized__c?: boolean
  Voltage__c?: nil | string
  Name?: nil | string
  Head_Tube_Angle2__c?: nil | string
  CreatedById?: nil | string
  PDLM__Required_Field_Warning__c?: nil | string | boolean
  Author__c?: nil | string
  Next_Review__c?: nil | string
  Market_Status__c?: nil | string
  Stand_Over_Height2__c?: nil | string
  Chain_Stay_Length2__c?: nil | string
  Width_Std__c?: nil | string
  LastViewedDate?: nil | string
  PDLM__Category_Control__c?: nil | string
  PDLM__Master_Item_Name__c?: nil | string
  PDLM__Released__c?: boolean
  Bottom_Bracket_Height__c?: nil | string
  PDLM__Master_Item_Number__c?: nil | string
  Custom_Field1__c?: nil | string
  CreatedDate?: nil | string
  Head_Tube_Length2__c?: nil | string
  PDLM__PrimaryKey__c?: nil | string
  PDLM__Description__c?: nil | string
  Last_Review__c?: nil | string
  PDLM__ProductCode__c?: nil | string
  Width_Metric__c?: nil | string
  PDLM__Rebaseline_Draft__c?: nil | string
  PDLM__Released_Date_Time__c?: nil | string
  LastReferencedDate?: nil | string
  CostRollup__c?: nil | string | number
  PDLM__Effective_Date1__c?: nil | string
  Density__c?: nil | string
  PDLM__Base_SKU__c?: nil | string
  Resistance__c?: nil | string
  Head_Tube_Length__c?: nil | string
  PDLM__Latest__c?: nil | string
  Navigation_Category__c?: nil | string
  Weight_Metric__c?: nil | string
  Currency__c?: nil | string
  PDLM__Released_Date__c?: nil | string
  Suggested_List_Price__c?: nil | string
  Reason_for_Change__c?: nil | string
  Brand__c?: nil | string
  put_a_number_here_just_because__c?: nil | string | number
  Publication_Site__c?: nil | string
  PDLM__Lifecycle_Phase__c?: nil | string
  PDLM__Aml_Count__c?: nil | string | number
  Document_Owner__c?: nil | string
  Seat_Tube_Angle__c?: nil | string
  PDLM__Has_Parent__c?: boolean
  Tariff__c?: nil | string | number
  Tech_Specs2__c?: nil | string
  PDLM__Master_Item__c?: nil | string
  LastModifiedById?: nil | string